### ISSUE TITLE
Should this library have a method for creating a connection to an existing session?

### ISSUE THREAD

**Issue by banagale** [marcsello/pyopenvidu#11]
Can you give a bit of feedback on the overall workflow for the creating a connection?

Looking at the official java client, [it appears that](https://docs.openvidu.io/en/2.15.0/api/openvidu-browser/classes/session.html#connect) session connections are always created by the `openvidu-browser` client.

So, this library would not need a way to create a connection. If a connection is made using the JS client, a signal from the session would update your custom application in some way.

Is that your understanding?

For example, using the example:

1. Initialize a Session 
```
    openvidu = OpenVidu(OPENVIDU_URL, OPENVIDU_SECRET)
    session = openvidu.create_session()
```
2. Get Token
```
token = session.generate_token()
```
3. Create Connection to a session
```
Performed by user's browser client openvidu-browser client, using token generated and made available to client.
```
4. Post connection operations are performed, user client polls for data perhaps prompted by signals created by the custom application.

**Comment by marcsello** [comment]
It seems to me that your understanding is correct. Connections are made by openvidu-browser (except for IPCAM https://docs.openvidu.io/en/2.15.0/reference-docs/REST-API/#post-apisessionsltsession_idgtconnection )

In order to work with the latest information, you have to call `fetch()`. I'd suggest you to write your program in a way, that it always calls `fetch()` before working with the list of the connections (e.g.: When using Flask, call `fetch` before processing any request). You can probably avoid working with outdated data this way.

If your application need to have a way to figure out when a connection is made (i.e.: a signal) you can use webhooks:
https://docs.openvidu.io/en/2.15.0/reference-docs/openvidu-server-webhook/

**Comment by banagale** [comment]
@marcsello Thank you for your feedback on this.
